language: python
python:
  - "3.7"
dist: bionic     # https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
install:
  - travis_retry pip install -r doc/requirements.txt
  - travis_retry pip install -r test/requirements.txt
  - travis_retry pip install coveralls
  - travis_retry pip install -e .
  - travis_retry git clone https://github.com/python/typeshed.git /tmp/typeshed
script:
  - py.test --cov=pymap
  - mypy --custom-typeshed-dir /tmp/typeshed pymap test
  - flake8 pymap test
after_success:
  - coveralls
  - make -C doc html
branches:
  only:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: doc/build/html
